import { ProductsGroup } from "../../types/api";

export const testingGroups: ProductsGroup[] = [
  {
    id: 0,
    title: "Тестовая группа 1",
    description: "Описание тестовой группы 1",
    products: [
      {
        id: 1,
        preview: "http://43306375.jpeg",
        images: [
          "http://43306375.jpeg",
          "http://25133982.png",
          "http://93661622.png",
          "http://1_3d.png",
          "http://2_3d.png",
          "http://45157942.png",
          "http://Frame_118.png",
        ],
        title: "Тестовый продукт 1 группы 1",
        subtitle: "Выберите один из восьми стикеров",
        price: 4199,
        description:
          "Выберите стикер, а мы перенесём его на ткань — как на фото. Одежду можно стирать в машинке при 30 °C, вывернув наизнанку. Гладить — с внутренней стороны. Посмотреть и потрогать все стикеры можно в A-Store на Технопарке. А ещё там можно добавить сразу несколько стикеров на одну вещь.",
        colors: ["white", "black", "red"],
        sizes: ["XS", "S", "M", "L", "XL"],
        stickerNumbers: [1, 2, 3, 4, 5, 6, 7, 8],
        availability: true,
      },
      {
        id: 2,
        preview: "http://43306375.jpeg",
        images: [
          "http://43306375.jpeg",
          "http://25133982.png",
          "http://93661622.png",
          "http://1_3d.png",
          "http://2_3d.png",
          "http://45157942.png",
          "http://Frame_118.png",
        ],
        title: "Тестовый продукт 2 группы 1",
        subtitle: "Выберите один из восьми стикеров",
        price: 3199,
        description:
          "Выберите стикер, а мы перенесём его на ткань — как на фото. Одежду можно стирать в машинке при 30 °C, вывернув наизнанку. Гладить — с внутренней стороны. Посмотреть и потрогать все стикеры можно в A-Store на Технопарке. А ещё там можно добавить сразу несколько стикеров на одну вещь.",
        colors: ["white"],
        sizes: ["XS", "S", "M"],
        stickerNumbers: [1, 2, 3, 4, 5],
        availability: true,
      },
      {
        id: 3,
        preview: "http://43306375.jpeg",
        images: [
          "http://43306375.jpeg",
          "http://25133982.png",
          "http://93661622.png",
          "http://1_3d.png",
          "http://2_3d.png",
          "http://45157942.png",
          "http://Frame_118.png",
        ],
        title: "Тестовый продукт 3 группы 1",
        subtitle: "Выберите один из восьми стикеров",
        price: 5199,
        description:
          "Выберите стикер, а мы перенесём его на ткань — как на фото. Одежду можно стирать в машинке при 30 °C, вывернув наизнанку. Гладить — с внутренней стороны. Посмотреть и потрогать все стикеры можно в A-Store на Технопарке. А ещё там можно добавить сразу несколько стикеров на одну вещь.",
        colors: ["black", "red"],
        sizes: ["XS", "S", "L", "XL"],
        stickerNumbers: [1, 2, 3],
        availability: true,
      },
    ],
  },
  {
    id: 1,
    title: "Тестовая группа 2",
    description: "Описание тестовой группы 2",
    products: [
      {
        id: 8,
        preview: "http://80077475.png",
        images: [
          "http://80077475.png",
          "http://75526651.png",
          "http://38611794.png",
          "http://72845408.png",
          "http://15216328.png",
          "http://88922367.png",
          "http://28363383.png",
          "http://5_3d.png",
          "http://45120806.png",
          "http://20347646.png",
          "http://8_3d.png",
          "http://Frame_118.png",
        ],
        title: "Тестовый продукт 1 группы 2",
        subtitle: "Выберите один из 20 стикеров",
        price: 4149,
        description:
          "Выберите стикер, а мы перенесём его на ткань — как на фото. Одежду можно стирать в машинке при 30 °C, вывернув наизнанку. Гладить — с внутренней стороны. Посмотреть и потрогать все стикеры можно в A-Store на Технопарке. А ещё там можно добавить сразу несколько стикеров на одну вещь.",
        colors: ["white", "black", "red"],
        sizes: ["XS", "S", "M", "L", "XL"],
        stickerNumbers: [
          1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
        ],
        availability: true,
      },
      {
        id: 9,
        preview: "http://qa-games.ru/astore/public/images/64963633.png",
        images: [
          "http://qa-games.ru/astore/public/images/64963633.png",
          "http://qa-games.ru/astore/public/images/61838715.png",
          "http://qa-games.ru/astore/public/images/33717334.png",
          "http://qa-games.ru/astore/public/images/40444416.png",
          "http://qa-games.ru/astore/public/images/51875593.png",
          "http://qa-games.ru/astore/public/images/72845408.png",
          "http://qa-games.ru/astore/public/images/15216328.png",
          "http://qa-games.ru/astore/public/images/88922367.png",
          "http://qa-games.ru/astore/public/images/28363383.png",
          "http://qa-games.ru/astore/public/images/5_3d.png",
          "http://qa-games.ru/astore/public/images/45120806.png",
          "http://qa-games.ru/astore/public/images/20347646.png",
          "http://qa-games.ru/astore/public/images/8_3d.png",
          "http://qa-games.ru/astore/public/images/Frame_117.png",
        ],
        title: "Тестовый продукт 2 группы 2",
        subtitle: "Все варианты — внутри",
        price: 1749,
        description:
          "Выберите стикер, а мы перенесём его на ткань — как на фото. Одежду можно стирать в машинке при 30 °C, вывернув наизнанку. Гладить — с внутренней стороны. Посмотреть и потрогать все стикеры можно в A-Store на Технопарке. А ещё там можно добавить сразу несколько стикеров на одну вещь.",
        colors: ["white", "black", "red", "green", "gray"],
        sizes: ["XS", "S", "M", "L", "XL", "XXL"],
        stickerNumbers: [
          1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
        ],
        availability: true,
      },
      {
        id: 10,
        preview: "http://qa-games.ru/astore/public/images/48495271.png",
        images: [
          "http://qa-games.ru/astore/public/images/48495271.png",
          "http://qa-games.ru/astore/public/images/88284218.png",
          "http://qa-games.ru/astore/public/images/33710051.png",
          "http://qa-games.ru/astore/public/images/43358772.png",
          "http://qa-games.ru/astore/public/images/43358772.png",
          "http://qa-games.ru/astore/public/images/72845408.png",
          "http://qa-games.ru/astore/public/images/15216328.png",
          "http://qa-games.ru/astore/public/images/88922367.png",
          "http://qa-games.ru/astore/public/images/28363383.png",
          "http://qa-games.ru/astore/public/images/5_3d.png",
          "http://qa-games.ru/astore/public/images/45120806.png",
          "http://qa-games.ru/astore/public/images/20347646.png",
          "http://qa-games.ru/astore/public/images/8_3d.png",
          "http://qa-games.ru/astore/public/images/Frame_119.png",
        ],
        title: "Тестовый продукт 3 группы 2",
        subtitle: "Нажмите, чтобы выбрать стикер",
        price: 1949,
        description:
          "Выберите стикер, а мы перенесём его на ткань — как на фото. Одежду можно стирать в машинке при 30 °C, вывернув наизнанку. Гладить — с внутренней стороны. Посмотреть и потрогать все стикеры можно в A-Store на Технопарке. А ещё там можно добавить сразу несколько стикеров на одну вещь.",
        colors: ["white", "black", "red", "gray"],
        sizes: ["S", "M", "L", "XL"],
        stickerNumbers: [
          1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
        ],
        availability: true,
      },
    ],
  },
];
